<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AdUser extends Model
{
    use HasFactory;
    /**
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'adempiere.ad_user';
    protected $primaryKey = 'ad_user_id';
    public $timestamps = false;
    /**
     * @var array
     */
    protected $fillable = [
        'ad_client_id',
        'ad_org_id',
        'isactive',
        'created',
        'createdby',
        'updated',
        'updatedby',
        'name',
        'description',
        'password',
        'email',
        'numinscritanem',
        'supervisor_id',
        'c_bpartner_id',
        'processing',
        'emailuser',
        'emailuserpw',
        'c_bpartner_location_id',
        'c_greeting_id',
        'title',
        'comments',
        'phone',
        'phone2',
        'fax',
        'lastcontact',
        'lastresult',
        'datenaiss',
        'ad_orgtrx_id',
        'emailverify',
        'emailverifydate',
        'notificationtype',
        'isfullbpaccess',
        'c_job_id',
        'ldapuser',
        'connectionprofile',
        'value',
        'userpin',
        'isinpayroll',
        'ad_user_uu',
        'ismenuautoexpand',
        'salt',
        'islocked',
        'dateaccountlocked',
        'failedlogincount',
        'datepasswordchanged',
        'datelastlogin',
        'isnopasswordreset',
        'isexpired',
        'securityquestion',
        'answer',
        'issaleslead',
        'c_location_id',
        'leadsource',
        'leadstatus',
        'leadsourcedescription',
        'leadstatusdescription',
        'c_campaign_id',
        'salesrep_id',
        'bpname',
        'bp_location_id',
        'isaddmailtextautomatically',
        'r_defaultmailtext_id',
        'ad_image_id',
        'adresse_pers',
        'service_nat',
        'inganneune',
        'ingannedeux',
        'ingannetrois',
        'ingannequatre',
        'ingannecinq',
        'ingannesix',
        'ingannesept',
        'ingmoyenneg',
        'masteranneune',
        'masterannedeux',
        'masterannetrois',
        'masterannequatre',
        'masterannecinq',
        'mastermoyenneg',
        'liccanneune',
        'liccannedeux',
        'liccannetrois',
        'liccannequatre',
        'liccmoyenneg',
        'liclmdanneune',
        'liclmdannedeux',
        'liclmdannetrois',
        'liclmdmoyenneg',
        'deuaanneune',
        'deuaannedeux',
        'deuaannetrois',
        'deuamoyenneg',
        'tsuanneune',
        'tsuannedeux',
        'tsuannetrois',
        'tsumoyenneg',
        'tsfpanneune',
        'tsfpannedeux',
        'tsfpannetrois',
        'tsfpmoyenneg',
        'sys_speciliteform_id',
        'sys_speciliteinscr_id',
        'hh_commune_id',
        'c_city_id',
        'sexe',
        'imageisattached',
        'imagelink',
        'imageurl',
        'sys_diplome',
        'sys_diplomecon_id',
        'iscondidat',
        'nom_institut',
        'commune_institut',
        'wilaya_institut',
        'nom',
        'prenom',
        'adresse',
        'sys_universites_id',
        'situation',
        'unique_id',
        'etat',
        'sys_specdiplome_id',
        'moyeng',
        'motif'
    ];
}
